name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 12
          - 14
          - 16
          - 18
          - 20

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm i

      - name: Lint, test, and build
        run: npm start validate

      - name: Check test coverage
        uses: codecov/codecov-action@v3
